/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.32
 * Generated at: 2012-10-28 10:29:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.protected_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


  if (request.getParameter("logoff") != null) {
    session.invalidate();
    response.sendRedirect("index.jsp");
    return;
  }

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Menu principal</title>\n");
      out.write("</head>\n");
      out.write("<body bgcolor=\"white\">\n");
      out.write("\n");
      out.write("<h1>MENU PRINCIPAL</h1><br><br>\n");

  	if (request.getUserPrincipal() != null) 
	{

      out.write("\n");
      out.write("    \t\tUsuari: <br>\n");
      out.write("    \t\t<b>");
      out.print( util.HTMLFilter.filter(request.getUserPrincipal().getName()) );
      out.write("</b>\n");
      out.write("    \t\t<br><br>\n");

  	} else {

      out.write("\n");
      out.write("    \t\tNo s'ha pogut identificar l'usuari.<br><br>\n");

  	}

      out.write("\n");
      out.write("\n");
      out.write("Sessio:<br> <b>");
      out.print( session.getId() );
      out.write("</b><br><br>\n");
      out.write("\n");
      out.write("Llistat de rols: <br>\n");

	// Aquesta variable la passarem entre pÃ gines a travÃ©s de la sessiÃ³:
	String rols = "";

	if (request.isUserInRole("G")) 
	{
		if (rols.equals(""))
		{
			rols = "G";
		}
		else
		{
			rols += ".G";
		}

      out.write("\n");
      out.write("      \t\t\n");
      out.write("      \t\t<b>Gerent</b><br>\n");

  	}

      out.write('\n');

	if (request.isUserInRole("DV")) 
	{
		if (rols.equals(""))
		{
			rols = "DV";
		}
		else
		{
			rols += ".DV";
		}

      out.write("\n");
      out.write("      \t\t\n");
      out.write("      \t\t<b>Direccio Ventes</b><br>\n");

  	}

      out.write('\n');

	if (request.isUserInRole("C")) 
	{
		if (rols.equals(""))
		{
			rols = "C";
		}
		else
		{
			rols += ".C";
		}

      out.write("\n");
      out.write("      \t\t\n");
      out.write("      \t\t<b>Comercial</b><br>\n");

  	}

      out.write('\n');

	if (request.isUserInRole("A")) 
	{
		if (rols.equals(""))
		{
			rols = "A";
		}
		else
		{
			rols += ".A";
		}

      out.write("\n");
      out.write("      \t\t\n");
      out.write("      \t\t<b>Administracio</b><br>\n");

  	}

      out.write('\n');

	if (request.isUserInRole("P")) 
	{
		if (rols.equals(""))
		{
			rols = "P";
		}
		else
		{
			rols += ".P";
		}

      out.write("\n");
      out.write("      \t\t\n");
      out.write("      \t\t<b>Produccio</b><br>\n");

  	}

      out.write('\n');

	if (request.isUserInRole("M")) 
	{
		if (rols.equals(""))
		{
			rols = "M";
		}
		else
		{
			rols += ".M";
		}

      out.write("\n");
      out.write("      \t\t\n");
      out.write("      \t\t<b>Magatzem</b><br>\n");

  	}

      out.write('\n');

	if (request.isUserInRole("T")) 
	{
		if (rols.equals(""))
		{
			rols = "T";
		}
		else
		{
			rols += ".T";
		}

      out.write("\n");
      out.write("      \t\t\n");
      out.write("      \t\t<b>Treballador</b><br>\n");

  	}

      out.write('\n');

	if (request.isUserInRole("CL")) 
	{
		if (rols.equals(""))
		{
			rols = "CL";
		}
		else
		{
			rols += ".CL";
		}

      out.write("\n");
      out.write("      \t\t\n");
      out.write("      \t\t<b>Client</b><br>\n");

  	}

	// Afegim el llistat de rols a la sessiÃ³ de l'usuari, si no existeix ja:
	if ((String)session.getAttribute("varUsuario") == null) 
	{
		session.putValue("rolsUsuari",rols); 
	}

      out.write("\n");
      out.write("\n");
      out.write("<br>\n");
      out.write("<a href='");
      out.print( response.encodeURL("ventes/index.jsp") );
      out.write("'>MODUL DE VENTES</a> <br>\n");
      out.write("<a href='");
      out.print( response.encodeURL("compres/index.jsp") );
      out.write("'>MODUL DE COMPRES</a> <br>\n");
      out.write("<a href='");
      out.print( response.encodeURL("rrhh/index.jsp") );
      out.write("'>MODUL DE RECURSOS HUMANS</a> <br>\n");
      out.write("<a href='");
      out.print( response.encodeURL("inventari/index.jsp") );
      out.write("'>MODUL D'INVENTARI</a> <br><br>\n");
      out.write("\n");
      out.write("<a href='");
      out.print( response.encodeURL("index.jsp?logoff=true") );
      out.write("'>Tancar sessio</a>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
